In [1]:
import pandas as pd

df = pd.read_csv('./mock.csv')

In [2]:
df = df.sort_values(['user_id', 'timestamp']).reset_index(drop=True)
df['prev_action_1'] = df.groupby('user_id')['action'].shift(1)
df['prev_action_2'] = df.groupby('user_id')['action'].shift(2)
df['prev_action_3'] = df.groupby('user_id')['action'].shift(3)

In [3]:
df[df.user_id == 'user_2']

,session_id,user_id,timestamp,action,parameters,prev_action_1,prev_action_2,prev_action_3
638,9dcec4bc-2ea3-47e0-ad15-58c796abd212,user_2,2025-03-01T12:04:05Z,GET /boards/{boardId},[],NaN,NaN,NaN
639,9dcec4bc-2ea3-47e0-ad15-58c796abd212,user_2,2025-03-01T12:10:27Z,PUT /invoices/{invoice_id}/status,"['status', 'invoice_id']",GET /boards/{boardId},NaN,NaN
640,9dcec4bc-2ea3-47e0-ad15-58c796abd212,user_2,2025-03-01T12:19:25Z,PATCH /tickets/{ticketId},"['priority', 'assignee', 'status']",PUT /invoices/{invoice_id}/status,GET /boards/{boardId},NaN
641,9dcec4bc-2ea3-47e0-ad15-58c796abd212,user_2,2025-03-01T12:22:20Z,POST /tickets/{ticketId}/transitions,['ticketId'],PATCH /tickets/{ticketId},PUT /invoices/{invoice_id}/status,GET /boards/{boardId}
642,9dcec4bc-2ea3-47e0-ad15-58c796abd212,user_2,2025-03-01T12:32:25Z,PUT /revenue/{service_id}/{revenue_id},[],POST /tickets/{ticketId}/transitions,PATCH /tickets/{ticketId},PUT /invoices/{invoice_id}/status
...,...,...,...,...,...,...,...,...
949,1d682671-7982-4768-8b51-f3047eee67d3,user_2,2025-05-26T16:20:00Z,POST /events,[],POST /sprints/{sprintId}/tickets,POST /tickets/{ticketId}/transitions,GET /events
950,1d682671-7982-4768-8b51-f3047eee67d3,user_2,2025-05-26T16:24:44Z,GET /sprints,"['board_id', 'state']",POST /events,POST /sprints/{sprintId}/tickets,POST /tickets/{ticketId}/transitions
951,41ced385-aab0-4e29-83fc-06d35f9688c6,user_2,2025-05-28T13:31:33Z,GET /events,['to_date'],GET /sprints,POST /events,POST /sprints/{sprintId}/tickets
952,41ced385-aab0-4e29-83fc-06d35f9688c6,user_2,2025-05-28T13:37:04Z,PUT /invoices/{invoice_id}/status,[],GET /events,GET /sprints,POST /events
953,41ced385-aab0-4e29-83fc-06d35f9688c6,user_2,2025-05-28T13:39:57Z,GET /events/{eventId},[],PUT /invoices/{invoice_id}/status,GET /events,GET /sprints

In [4]:
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['day'] = df['timestamp'].dt.day
df['month'] = df['timestamp'].dt.month
df['week'] = df['timestamp'].dt.isocalendar().week
df['year'] = df['timestamp'].dt.year
df['seconds_passed'] = (df['timestamp'].dt.hour * 3600 +
df['timestamp'].dt.minute * 60 +
df['timestamp'].dt.second)

In [5]:
df['pa1_ss'] = df['session_id'] == df.groupby('user_id')['session_id'].shift(1)
df['pa2_ss'] = df['session_id'] == df.groupby('user_id')['session_id'].shift(2)
df['pa3_ss'] = df['session_id'] == df.groupby('user_id')['session_id'].shift(3)

In [6]:
df.to_csv('cleaned.csv', index=False)